"""Controladores, perfiles, setups y resultados de corridas (EN-04)."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005_operaciones"
down_revision = "0004_versiones"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controlador",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("nombre_corto", sa.String(length=30), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("parametros", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("presets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("jsonb_typeof(parametros) = 'array'", name="ck_controlador_parametros"),
        sa.CheckConstraint("jsonb_typeof(presets) = 'object'", name="ck_controlador_presets"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "perfil_reglamento",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("competencia", sa.String(length=120), nullable=False),
        sa.Column("etiqueta", sa.String(length=20), nullable=False),
        sa.Column("categoria", sa.String(length=120), nullable=False),
        sa.Column("reglas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("jsonb_typeof(reglas) = 'object'", name="ck_perfil_reglas"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "setup",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("controlador_id", sa.String(length=40), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("parametros", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("controlador_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("archivado", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("btrim(nombre) <> ''", name="ck_setup_nombre"),
        sa.CheckConstraint(
            "jsonb_typeof(controlador_snapshot) = 'object'", name="ck_setup_snapshot"
        ),
        sa.CheckConstraint("jsonb_typeof(parametros) = 'object'", name="ck_setup_parametros"),
        sa.CheckConstraint("id BETWEEN 1 AND 9007199254740991", name="ck_setup_id"),
        sa.ForeignKeyConstraint(["controlador_id"], ["controlador.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["version_id"], ["version.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "version_id", name="uq_setup_version"),
    )
    op.create_index(op.f("ix_setup_controlador_id"), "setup", ["controlador_id"], unique=False)
    op.create_index(op.f("ix_setup_version_id"), "setup", ["version_id"], unique=False)
    op.create_table(
        "corrida",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("numero", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("setup_id", sa.BigInteger(), nullable=False),
        sa.Column("perfil_id", sa.String(length=40), nullable=False),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cerrada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fuente", sa.String(length=10), nullable=False),
        sa.Column("modo", sa.String(length=15), nullable=False),
        sa.Column("linea", sa.String(length=10), nullable=False),
        sa.Column("compensa_bateria", sa.Boolean(), nullable=False),
        sa.Column("potencia_turbina_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("contexto_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nota", sa.Text(), server_default="", nullable=False),
        sa.CheckConstraint("fuente IN ('sim','robot')", name="ck_corrida_fuente"),
        sa.CheckConstraint(
            "jsonb_typeof(contexto_snapshot) = 'object'", name="ck_corrida_snapshot"
        ),
        sa.CheckConstraint("linea IN ('negra','blanca')", name="ck_corrida_linea"),
        sa.CheckConstraint("modo IN ('prueba','competencia')", name="ck_corrida_modo"),
        sa.CheckConstraint("cerrada_en IS NULL OR cerrada_en >= fecha", name="ck_corrida_fechas"),
        sa.CheckConstraint("char_length(nota) <= 1000", name="ck_corrida_nota"),
        sa.CheckConstraint("id BETWEEN 1 AND 9007199254740991", name="ck_corrida_id"),
        sa.CheckConstraint("numero > 0", name="ck_corrida_numero"),
        sa.CheckConstraint("potencia_turbina_pct BETWEEN 0 AND 100", name="ck_corrida_turbina"),
        sa.ForeignKeyConstraint(["perfil_id"], ["perfil_reglamento.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["setup_id", "version_id"],
            ["setup.id", "setup.version_id"],
            name="fk_corrida_setup_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["version_id"], ["version.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero"),
    )
    op.create_index(op.f("ix_corrida_fecha"), "corrida", ["fecha"], unique=False)
    op.create_index(op.f("ix_corrida_perfil_id"), "corrida", ["perfil_id"], unique=False)
    op.create_index(op.f("ix_corrida_setup_id"), "corrida", ["setup_id"], unique=False)
    op.create_index(op.f("ix_corrida_version_id"), "corrida", ["version_id"], unique=False)
    op.create_table(
        "vuelta",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("corrida_id", sa.BigInteger(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("tiempo_s", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("duracion_s", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("tiempo_interno_ms", sa.BigInteger(), nullable=True),
        sa.Column("error_acumulado", sa.Numeric(precision=18, scale=9), nullable=False),
        sa.Column("lineas_perdidas", sa.Integer(), nullable=False),
        sa.Column("bateria_v", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("termino", sa.Boolean(), nullable=False),
        sa.Column("fuente_tiempo", sa.String(length=15), nullable=False),
        sa.Column("motivo", sa.Text(), server_default="", nullable=False),
        sa.CheckConstraint(
            "(termino AND tiempo_s IS NOT NULL AND tiempo_s >= 0 AND tiempo_s <> 'NaN'::numeric) OR (NOT termino AND tiempo_s IS NULL)",
            name="ck_vuelta_tiempo",
        ),
        sa.CheckConstraint(
            "duracion_s >= 0 AND duracion_s <> 'NaN'::numeric AND error_acumulado >= 0 AND error_acumulado <> 'NaN'::numeric AND bateria_v >= 0 AND bateria_v <> 'NaN'::numeric",
            name="ck_vuelta_medidas",
        ),
        sa.CheckConstraint("fuente_tiempo IN ('meta','telemetria')", name="ck_vuelta_fuente"),
        sa.CheckConstraint("char_length(motivo) <= 500", name="ck_vuelta_motivo"),
        sa.CheckConstraint("id BETWEEN 1 AND 9007199254740991", name="ck_vuelta_id"),
        sa.CheckConstraint("numero > 0 AND lineas_perdidas >= 0", name="ck_vuelta_contadores"),
        sa.CheckConstraint(
            "tiempo_interno_ms IS NULL OR tiempo_interno_ms >= 0", name="ck_vuelta_interno"
        ),
        sa.ForeignKeyConstraint(["corrida_id"], ["corrida.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corrida_id", "numero", name="uq_vuelta_numero"),
    )
    op.create_index(op.f("ix_vuelta_corrida_id"), "vuelta", ["corrida_id"], unique=False)
    op.create_table(
        "sector_vuelta",
        sa.Column("vuelta_id", sa.BigInteger(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("tiempo_s", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.CheckConstraint(
            "numero > 0 AND tiempo_s >= 0 AND tiempo_s <> 'NaN'::numeric", name="ck_sector_medidas"
        ),
        sa.ForeignKeyConstraint(["vuelta_id"], ["vuelta.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("vuelta_id", "numero"),
    )
    op.create_table(
        "segmento_vuelta",
        sa.Column("vuelta_id", sa.BigInteger(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("duracion_s", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("angulo_grados", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("error_acumulado", sa.Numeric(precision=18, scale=9), nullable=False),
        sa.CheckConstraint(
            "numero > 0 AND duracion_s >= 0 AND duracion_s <> 'NaN'::numeric AND error_acumulado >= 0 AND error_acumulado <> 'NaN'::numeric AND angulo_grados <> 'NaN'::numeric",
            name="ck_segmento_medidas",
        ),
        sa.ForeignKeyConstraint(["vuelta_id"], ["vuelta.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("vuelta_id", "numero"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("segmento_vuelta")
    op.drop_table("sector_vuelta")
    op.drop_table("vuelta")
    op.drop_table("corrida")
    op.drop_table("setup")
    op.drop_table("perfil_reglamento")
    op.drop_table("controlador")
    # ### end Alembic commands ###
